services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: local_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@localhost.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_NAME: local_db
      JWT_SECRET: teeradon
      CONNECTION_STRING: postgresql://root:1234@db:5432/local_db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  local_pgdata:
  pgadmin-data:
